// config/autoResponses.js

export const KEYWORD_REPLIES = {
  // ================================================================
  // 1. التحيات العربية (50)
  // ================================================================
  'سلام': 'وعليكم السلام',
  'السلام': 'وعليكم السلام',
  'السلام عليكم': 'وعليكم السلام ورحمة الله وبركاته',
  'هلا': 'هلا والله',
  'هلا بيك': 'هلا وغلا',
  'اهلا': 'أهلاً وسهلاً',
  'أهلا': 'أهلاً وسهلاً',
  'مرحبا': 'مرحباً بك',
  'مرحباً': 'مرحباً بك',
  'الو': 'ألوووو، أهلاً بك',
  'هلو': 'هلوووو',
  'ايوه': 'ايوه يا باشا',
  'اية': 'أية يا عم؟',
  'حياك الله': 'الله يحييك',
  'حي الله': 'الله يحييك',
  'أهلاً': 'أهلاً بك',
  'أهلا وسهلا': 'أهلاً وسهلاً',
  'مرحبتين': 'مرحبتين بألف',
  'يا هلا': 'يا هلا وغلا',
  'يا مرحبا': 'يا مرحبا بك',
  'نورت': 'نورت والله',
  'نورتنا': 'نورتنا والله',
  'تشرفنا': 'تشرفنا والله',
  'تشرفت': 'تشرفت والله',
  'منور': 'منور والله',
  'المنور': 'المنور أنت',
  'أهلاً بك': 'أهلاً بك يا حبيبي',
  'هلا والله': 'هلا والله',
  'هلا هلا': 'هلا هلا بيك',
  'حي': 'حي الله',
  'تحياتي': 'تحياتي لك',
  'سلامي': 'سلامي لك',
  'سلامو': 'سلامو عليكو',
  'يا سلام': 'يا سلام عليك',
  'سلاااام': 'وعليكم السلام',
  'هلااا': 'هلاااا بك',
  'مرحباا': 'مرحباً بك',
  'أهلاا': 'أهلاً وسهلاً',
  'الوو': 'الوووو',
  'الووو': 'الووووو',
  'هلوو': 'هلوووو',
  'هلووو': 'هلووووو',
  'اي': 'ايوا',
  'آه': 'آه يا عم',
  'أه': 'أهلاً',
  'يا': 'يا باشا',
  'يابا': 'يابا يا عم',
  'بابا': 'بابا مين؟ 😄',
  'ماما': 'ماما مين؟ 😄',
  'تيتا': 'تيتا مين؟ 😄',

  // ================================================================
  // 2. السؤال عن الحال (عربي) (50)
  // ================================================================
  'كيفك': 'الحمد لله، وإنت؟',
  'كيف حالك': 'الحمد لله، وإنت؟',
  'كيف الحال': 'الحمد لله، أخبارك إيه؟',
  'اخبارك': 'الحمد لله، أخبارك إيه؟',
  'اخبارك ايه': 'الحمد لله، أخبارك إيه؟',
  'ايه اخبارك': 'الحمد لله، أخبارك إيه؟',
  'عامل ايه': 'الحمد لله، وإنت عامل إيه؟',
  'عامل اي': 'الحمد لله، وإنت عامل إيه؟',
  'ازيك': 'أنا زي الفل، وإنت؟',
  'ازاي': 'أنا زي الفل، وإنت؟',
  'ايه اخبار': 'كلو تمام، وإنت؟',
  'شخبارك': 'الحمد لله، وشخبارك إنت؟',
  'اخبار ايه': 'كلو تمام',
  'أخبار': 'أخبارك إيه؟',
  'أخبارك': 'أخبارك إيه؟',
  'أخبار ايه': 'كلو تمام',
  'أخبارك ايه': 'كلو تمام',
  'أي اخبار': 'كلو تمام',
  'أي أخبار': 'كلو تمام',
  'عامل': 'عامل إيه؟',
  'عامل ايه': 'عامل إيه؟',
  'عامل اي': 'عامل إيه؟',
  'عاملين': 'عاملين إيه؟',
  'عاملين ايه': 'عاملين إيه؟',
  'عاملين اي': 'عاملين إيه؟',
  'شو أخبارك': 'كلو تمام',
  'شو اخبارك': 'كلو تمام',
  'شو عامل': 'شو عامل؟',
  'شو عامل ايه': 'شو عامل؟',
  'شو عامل اي': 'شو عامل؟',
  'شو صاير': 'أهلاً وسهلاً',
  'شو صاير معك': 'أهلاً وسهلاً',
  'كيف الأحوال': 'الحمد لله',
  'كيف الأمور': 'تمام',
  'كيف الحياة': 'زي الفل',
  'كيف الدنيا': 'الدنيا تمام',
  'كيف العالم': 'العالم تمام',
  'كيف الحال اليوم': 'الحمد لله',
  'كيف حالك اليوم': 'الحمد لله',
  'كيف أنت': 'أنا بخير',
  'كيف أنت اليوم': 'أنا بخير',
  'كيف انت': 'أنا بخير',
  'كيف انت اليوم': 'أنا بخير',
  'كيف تكون': 'أنا بخير',
  'كيف تكون اليوم': 'أنا بخير',
  'كيفك اليوم': 'أنا بخير',
  'كيفك انت': 'أنا بخير',
  'كيفك انت اليوم': 'أنا بخير',
  'كيفك انتي': 'أنا بخير',
  'كيفك انتي اليوم': 'أنا بخير',

  // ================================================================
  // 3. الردود على الشكر والدعاء (عربي) (50)
  // ================================================================
  'شكرا': 'العفو، تحت أمرك',
  'شكراً': 'العفو، تحت أمرك',
  'شكرا جزيلا': 'الشكر لله',
  'شكراً جزيلاً': 'الشكر لله',
  'شكرا لك': 'العفو',
  'شكراً لك': 'العفو',
  'تسلم': 'تسلم يا رب',
  'تسلملي': 'تسلملي أنت',
  'يسلمو': 'يسلمو يا رب',
  'يسلملي': 'يسلملي أنت',
  'يعطيك العافية': 'يعافيك يا رب',
  'بالتوفيق': 'الله يوفقك يا رب',
  'ربنا معاك': 'الله معاك يارب',
  'الله يخليك': 'الله يخليك ويبارك فيك',
  'حبيبي': 'حبيبي والله',
  'حبيبتي': 'حبيبتي والله',
  'يا حبيبي': 'يا حبيبي يا روحي',
  'يا عم': 'يا عم والله',
  'يا باشا': 'أمرك يا باشا',
  'يا كبير': 'أمرك يا كبير',
  'يا معلم': 'أمرك يا معلم',
  'يا استاذ': 'أمرك يا استاذ',
  'يا دكتور': 'أمرك يا دكتور',
  'يا مهندس': 'أمرك يا مهندس',
  'يا غالي': 'أمرك يا غالي',
  'يا عسل': 'أمرك يا عسل',
  'يا قمر': 'أمرك يا قمر',
  'يا نجم': 'أمرك يا نجم',
  'يا بطل': 'أمرك يا بطل',
  'يا زعيم': 'أمرك يا زعيم',
  'يا ملك': 'أمرك يا ملك',
  'يا فارس': 'أمرك يا فارس',
  'يا صديق': 'أمرك يا صديق',
  'يا رفيق': 'أمرك يا رفيق',
  'يا أخي': 'أمرك يا أخي',
  'يا أختي': 'أمرك يا أختي',
  'يا ولد': 'أمرك يا ولد',
  'يا بنت': 'أمرك يا بنت',
  'يا رجالة': 'أمرك يا رجالة',
  'يا ستات': 'أمرك يا ستات',
  'يا جماعة': 'أمرك يا جماعة',
  'يا ناس': 'أمرك يا ناس',
  'يا عالم': 'أمرك يا عالم',
  'يا خلق الله': 'أمرك يا خلق الله',
  'يا رب': 'اللهم آمين',
  'يا الله': 'اللهم لبيك',
  'يالله': 'اللهم لبيك',
  'ياله': 'أهلاً',
  'يالا': 'يلا بينا',
  'يلا': 'يلا بينا',
  'يلا بينا': 'يلا بينا يا باشا',

  // ================================================================
  // 4. صباح الخير ومساء الخير (عربي) (50)
  // ================================================================
  'صباح الخير': 'صباح النور والسرور',
  'صباح النور': 'صباح الفل والياسمين',
  'صباحو': 'صباح الخير',
  'صباح الورد': 'صباح الفل',
  'صباح الياسمين': 'صباح النور',
  'صباح الفل': 'صباح الخير',
  'صباح العسل': 'صباح النور',
  'صباح السكر': 'صباح الخير',
  'صباح العطر': 'صباح النور',
  'صباح الجمال': 'صباح الخير',
  'مساء الخير': 'مساء الفل والياسمين',
  'مساء النور': 'مساء الفل والياسمين',
  'مساءو': 'مساء الخير',
  'مساء الورد': 'مساء الفل',
  'مساء الياسمين': 'مساء النور',
  'مساء الفل': 'مساء الخير',
  'مساء العسل': 'مساء النور',
  'مساء السكر': 'مساء الخير',
  'مساء العطر': 'مساء النور',
  'مساء الجمال': 'مساء الخير',
  'تصبح على خير': 'تصبح على خير يا رب',
  'تصبحي على خير': 'تصبحي على خير يا رب',
  'تصبحوا على خير': 'تصبحوا على خير',
  'تصبحين على خير': 'تصبحين على خير',
  'تصبح على ورد': 'تصبح على ورد',
  'تصبح على عسل': 'تصبح على عسل',
  'طاب مسائكم': 'طاب مساؤك',
  'طاب صباحكم': 'طاب صباحك',
  'طابت ليلتكم': 'طابت ليلتك',
  'طابت أوقاتكم': 'طابت أوقاتك',
  'سهرة سعيدة': 'سهرة سعيدة عليك',
  'ليل سعيد': 'ليل سعيد عليك',
  'نهار سعيد': 'نهار سعيد عليك',
  'يوم سعيد': 'يوم سعيد عليك',
  'أسبوع سعيد': 'أسبوع سعيد عليك',
  'شهر سعيد': 'شهر سعيد عليك',
  'عام سعيد': 'عام سعيد عليك',
  'النهاردة': 'النهاردة يوم جميل',
  'الليلة': 'الليلة ليلة جميلة',
  'بكرة': 'بكرة يوم جديد',
  'غدا': 'غدا يوم جديد',
  'بعد بكرة': 'بعد بكرة يوم جديد',
  'أمس': 'أمس كان يوم جميل',
  'الأمس': 'الأمس كان يوم جميل',
  'أول أمس': 'أول أمس كان يوم جميل',
  'البارحة': 'البارحة كانت ليلة جميلة',
  'أول ما': 'أول ما تشوف',
  'ما': 'ما فيش مشكلة',
  'مش': 'مش مشكلة',
  'مشكلة': 'مشكلة إيه؟',

  // ================================================================
  // 5. الأذكار والدين (عربي) (50)
  // ================================================================
  'الحمدلله': 'الحمد لله دائماً وأبداً',
  'الحمد لله': 'الحمد لله دائماً وأبداً',
  'سبحان الله': 'سبحان الله وبحمده',
  'سبحان الله وبحمده': 'سبحان الله العظيم',
  'سبحان الله العظيم': 'سبحان الله وبحمده',
  'لا اله الا الله': 'لا إله إلا الله وحده لا شريك له',
  'لا إله إلا الله': 'لا إله إلا الله وحده لا شريك له',
  'الله اكبر': 'الله أكبر كبيراً',
  'الله أكبر': 'الله أكبر كبيراً',
  'ماشاء الله': 'تبارك الله',
  'ما شاء الله': 'تبارك الله',
  'ان شاء الله': 'إن شاء الله خير',
  'إن شاء الله': 'إن شاء الله خير',
  'استغفر الله': 'أستغفر الله العظيم وأتوب إليه',
  'أستغفر الله': 'أستغفر الله العظيم وأتوب إليه',
  'ربنا': 'ربنا موجود يا حبيبي',
  'ربنا معانا': 'ربنا معانا إن شاء الله',
  'ربنا يسهل': 'ربنا يسهل علينا',
  'ربنا يوفق': 'ربنا يوفقك',
  'ربنا يحميك': 'ربنا يحميك',
  'ربنا يبارك': 'ربنا يبارك فيك',
  'ربنا يرزقك': 'ربنا يرزقك',
  'ربنا يشفيك': 'ربنا يشفيك',
  'ربنا يعينك': 'ربنا يعينك',
  'ربنا ينجيك': 'ربنا ينجيك',
  'ربنا يصلحك': 'ربنا يصلحك',
  'ربنا يهديك': 'ربنا يهديك',
  'ربنا يصلح حالك': 'ربنا يصلح حالك',
  'ربنا يفرجها': 'ربنا يفرجها',
  'ربنا يفرج همك': 'ربنا يفرج همك',
  'ربنا يخليك': 'ربنا يخليك',
  'ربنا يسلمك': 'ربنا يسلمك',
  'ربنا يحفظك': 'ربنا يحفظك',
  'ربنا يرعاك': 'ربنا يرعاك',
  'ربنا ينصرك': 'ربنا ينصرك',
  'ربنا يقويك': 'ربنا يقويك',
  'ربنا يزيدك': 'ربنا يزيدك',
  'ربنا يعزك': 'ربنا يعزك',
  'ربنا يكرمك': 'ربنا يكرمك',
  'ربنا يرفعك': 'ربنا يرفعك',
  'ربنا يعلو شأنك': 'ربنا يعلو شأنك',
  'ربنا يكتبلك الخير': 'ربنا يكتبلك الخير',
  'ربنا يرضى عنك': 'ربنا يرضى عنك',
  'ربنا يجمعنا': 'ربنا يجمعنا',
  'ربنا يتوب عليك': 'ربنا يتوب عليك',
  'ربنا يغفرلك': 'ربنا يغفرلك',
  'ربنا يرحمك': 'ربنا يرحمك',
  'ربنا يديم النعمة': 'ربنا يديم النعمة',
  'ربنا يدوم عليك': 'ربنا يدوم عليك',

  // ================================================================
  // 6. الردود العامة (عربي) (50)
  // ================================================================
  'بوت': 'أنا بوت Void_Syndicate، تحت أمرك',
  'مين انت': 'أنا بوت Void_Syndicate، تحت أمرك',
  'مين أنت': 'أنا بوت Void_Syndicate، تحت أمرك',
  'انت مين': 'أنا بوت Void_Syndicate، تحت أمرك',
  'أنت مين': 'أنا بوت Void_Syndicate، تحت أمرك',
  'باي': 'باي باي، سلام',
  'مع السلامة': 'مع السلامة، أراك قريباً',
  'يلا': 'يلا بينا',
  'يلا بينا': 'يلا بينا يا باشا',
  'خلصت': 'خلصت؟ تمام',
  'تمام': 'تمام يا باشا',
  'اوكي': 'أوكي يا معلم',
  'اوك': 'أوكي يا معلم',
  'يعني': 'يعني إيه؟ مش فاهم',
  'مش فاهم': 'أنا كمان مش فاهم',
  'فهمت': 'أنا كمان فهمت',
  'فهمتيني': 'أنا كمان فهمت',
  'جبتها': 'جامد فشخ',
  'جامد': 'جامد أنت',
  'فشخ': 'فشخ يعني أوي',
  'بتاع': 'بتاع إيه؟',
  'العب': 'أنا بوت مش بلعب',
  'شغال': 'شغال يا باشا',
  'شغالة': 'شغالة يا باشا',
  'شغالين': 'شغالين يا باشا',
  'شغالة معاك': 'شغالة معاك',
  'أهو': 'أهو يا عم',
  'أهي': 'أهي يا عم',
  'أهوه': 'أهوه يا عم',
  'أهييي': 'أهييي',
  'ألو': 'ألووو',
  'ألوا': 'ألواااا',
  'ألوه': 'ألوههه',
  'أه': 'أهلاً',
  'آه': 'آه يا عم',
  'آآه': 'آآه',
  'أآآه': 'أآآه',
  'أأأ': 'أأأ',
  'ييي': 'ييي',
  'أيي': 'أيي',
  'أوو': 'أوو',
  'آو': 'آو',
  'أو': 'أو',
  'آ': 'آه',
  'إ': 'إيه',
  'إيه': 'إيه يا عم',
  'ايه': 'ايه يا عم',
  'أي': 'أي',
  'أييي': 'أييي',
  'أيوة': 'أيوة يا باشا',

  // ================================================================
  // 7. المزاح والفرفشة (عربي) (50)
  // ================================================================
  'هههه': 'هههههههه',
  'ههه': 'ههههه',
  'هههههه': 'ههههههههههه',
  'ضحك': 'هههههههه',
  'نكتة': 'قول نكتة',
  'قول نكتة': 'مرة واحد بوت قال لأخوه...',
  'جبتها': 'جامد فشخ',
  'جامد': 'جامد أنت',
  'فشخ': 'فشخ يعني أوي',
  'بتاع': 'بتاع إيه؟',
  'العب': 'أنا بوت مش بلعب',
  'شغال': 'شغال يا باشا',
  'عسل': 'عسل أنت',
  'سكر': 'سكر أنت',
  'قطر': 'قطر أنت',
  'حلو': 'حلو أنت',
  'جميل': 'جميل أنت',
  'وسيم': 'وسيم أنت',
  'جميلة': 'جميلة أنت',
  'حلوة': 'حلوة أنت',
  'وسيمة': 'وسيمة أنت',
  'ملاك': 'ملاك أنت',
  'ملك': 'ملك أنت',
  'ملكة': 'ملكة أنت',
  'أمير': 'أمير أنت',
  'أميرة': 'أميرة أنت',
  'فارس': 'فارس أنت',
  'فارسة': 'فارسة أنت',
  'بطل': 'بطل أنت',
  'بطلة': 'بطلة أنت',
  'نجم': 'نجم أنت',
  'نجمة': 'نجمة أنت',
  'قمر': 'قمر أنت',
  'قمرة': 'قمرة أنت',
  'شمس': 'شمس أنت',
  'شمسة': 'شمسة أنت',
  'نور': 'نور أنت',
  'نورة': 'نورة أنت',
  'ضيا': 'ضيا أنت',
  'ضياء': 'ضياء أنت',
  'منور': 'منور أنت',
  'منورة': 'منورة أنت',
  'نورتي': 'نورتي أنت',
  'نورتني': 'نورتني أنت',
  'فرحتني': 'فرحتني أنت',
  'أسعدتني': 'أسعدتني أنت',
  'بهجتني': 'بهجتني أنت',
  'سعدتني': 'سعدتني أنت',
  'ضحكتني': 'ضحكتني أنت',

  // ================================================================
  // 8. الأوامر (عربي) (50)
  // ================================================================
  'help': 'الأوامر: \n!help - مساعدة \n!ping - زمن الاتصال \n!server - معلومات السيرفر',
  'مساعدة': 'اكتب !help عشان تشوف الأوامر',
  'اوامر': 'اكتب !help عشان تشوف الأوامر',
  'الأوامر': 'اكتب !help عشان تشوف الأوامر',
  'الاوامر': 'اكتب !help عشان تشوف الأوامر',
  'أوامر': 'اكتب !help عشان تشوف الأوامر',
  'أمر': 'اكتب !help عشان تشوف الأوامر',
  'أوامرك': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوتات': 'اكتب !help عشان تشوف الأوامر',
  'الأوامر المتاحة': 'اكتب !help عشان تشوف الأوامر',
  'الاوامر المتاحة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر متاحة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر جديدة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر قديمة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر سرية': 'اكتب !help عشان تشوف الأوامر',
  'أوامر مهمة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر خاصة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر عامة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر ممنوعة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر مسموحة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت الجديدة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت القديمة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت السرية': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت المهمة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت الخاصة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت العامة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت الممنوعة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت المسموحة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت المتاحة': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت الجديدة 2': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت القديمة 2': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت السرية 2': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت المهمة 2': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت الخاصة 2': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت العامة 2': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت الممنوعة 2': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت المسموحة 2': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت المتاحة 2': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت الجديدة 3': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت القديمة 3': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت السرية 3': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت المهمة 3': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت الخاصة 3': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت العامة 3': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت الممنوعة 3': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت المسموحة 3': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت المتاحة 3': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت الجديدة 4': 'اكتب !help عشان تشوف الأوامر',
  'أوامر البوت القديمة 4': 'اكتب !help عشان تشوف الأوامر',

  // ================================================================
  // 9. Greetings (English) (50)
  // ================================================================
  'hello': 'Hello there!',
  'hi': 'Hi! How are you?',
  'hey': 'Hey! How can I help?',
  'greetings': 'Greetings to you!',
  'good morning': 'Good morning! Have a great day',
  'good afternoon': 'Good afternoon!',
  'good evening': 'Good evening!',
  'good night': 'Good night! Sleep well',
  'hey there': 'Hey there!',
  'yo': 'Yo! What\'s up?',
  'sup': 'Sup! How are you?',
  'what\'s up': 'Not much! What about you?',
  'howdy': 'Howdy partner!',
  'hi there': 'Hi there!',
  'hello there': 'Hello there!',
  'hallo': 'Hallo!',
  'hallo there': 'Hallo there!',
  'hola': 'Hola!',
  'hola there': 'Hola there!',
  'ciao': 'Ciao!',
  'ciao there': 'Ciao there!',
  'namaste': 'Namaste!',
  'namaste there': 'Namaste there!',
  'salaam': 'Salaam!',
  'salaam there': 'Salaam there!',
  'shalom': 'Shalom!',
  'shalom there': 'Shalom there!',
  'bonjour': 'Bonjour!',
  'bonjour there': 'Bonjour there!',
  'guten tag': 'Guten tag!',
  'guten tag there': 'Guten tag there!',
  'konnichiwa': 'Konnichiwa!',
  'konnichiwa there': 'Konnichiwa there!',
  'ni hao': 'Ni hao!',
  'ni hao there': 'Ni hao there!',
  'privet': 'Privet!',
  'privet there': 'Privet there!',
  'hei': 'Hei!',
  'hei there': 'Hei there!',
  'hej': 'Hej!',
  'hej there': 'Hej there!',
  'hallo again': 'Hallo again!',
  'hello again': 'Hello again!',
  'hi again': 'Hi again!',
  'hey again': 'Hey again!',
  'yo again': 'Yo again!',
  'sup again': 'Sup again!',
  'what\'s up again': 'What\'s up again!',
  'howdy again': 'Howdy again!',
  'greetings again': 'Greetings again!',
  'good morning again': 'Good morning again!',

  // ================================================================
  // 10. Questions (English) (50)
  // ================================================================
  'how are you': 'I\'m fine, thanks! And you?',
  'how r u': 'I\'m good! And you?',
  'how are you doing': 'I\'m doing great!',
  'what are you doing': 'Just chatting with you!',
  'what do you do': 'I\'m a bot, I chat with people!',
  'what is your name': 'My name is Void_Syndicate Bot',
  'who are you': 'I\'m Void_Syndicate, your friendly bot',
  'where are you from': 'I\'m from the cloud!',
  'what time is it': 'Check your phone!',
  'what day is it': 'Every day is a good day!',
  'how are u': 'I\'m good! And you?',
  'how r u doing': 'I\'m doing great!',
  'how are u doing': 'I\'m doing great!',
  'what r u doing': 'Just chatting with you!',
  'what u doing': 'Just chatting with you!',
  'what you doing': 'Just chatting with you!',
  'what up': 'Not much! What about you?',
  'wassup': 'Not much! What about you?',
  'sup bro': 'Sup! How are you?',
  'sup bro?': 'Sup! How are you?',
  'yo bro': 'Yo! What\'s up?',
  'hey bro': 'Hey! How can I help?',
  'hi bro': 'Hi! How are you?',
  'hello bro': 'Hello there!',
  'what\'s your name': 'My name is Void_Syndicate Bot',
  'whats your name': 'My name is Void_Syndicate Bot',
  'your name': 'My name is Void_Syndicate Bot',
  'name': 'My name is Void_Syndicate Bot',
  'who r u': 'I\'m Void_Syndicate, your friendly bot',
  'who r you': 'I\'m Void_Syndicate, your friendly bot',
  'where r u': 'I\'m from the cloud!',
  'where u from': 'I\'m from the cloud!',
  'what time': 'Check your phone!',
  'what day': 'Every day is a good day!',
  'what is today': 'Every day is a good day!',
  'what is tomorrow': 'Tomorrow is a new day!',
  'what is yesterday': 'Yesterday was a good day!',
  'what is life': 'Life is beautiful!',
  'what is love': 'Love is everything!',
  'what is happiness': 'Happiness is a choice!',
  'what is success': 'Success is a journey!',
  'what is failure': 'Failure is a stepping stone!',
  'what is hope': 'Hope is a light!',
  'what is faith': 'Faith is a shield!',
  'what is trust': 'Trust is a bond!',
  'what is loyalty': 'Loyalty is a treasure!',
  'what is friendship': 'Friendship is a gift!',
  'what is family': 'Family is everything!',
  'what is home': 'Home is where the heart is!',
  'what is peace': 'Peace is a state of mind!',

  // ================================================================
  // 11. Thanks (English) (50)
  // ================================================================
  'thanks': 'You\'re welcome!',
  'thank you': 'You\'re welcome!',
  'thank u': 'You\'re welcome!',
  'ty': 'You\'re welcome!',
  'thx': 'Anytime!',
  'appreciate it': 'I appreciate you too!',
  'you are great': 'You are greater!',
  'you are awesome': 'No, you are awesome!',
  'i love you': 'I love you too!',
  'love': 'Love you too!',
  'miss you': 'Miss you too!',
  'i miss you': 'I miss you too!',
  'thank you so much': 'You\'re welcome!',
  'thanks a lot': 'You\'re welcome!',
  'many thanks': 'You\'re welcome!',
  'thanks buddy': 'You\'re welcome!',
  'thanks bro': 'You\'re welcome!',
  'thanks dude': 'You\'re welcome!',
  'thanks man': 'You\'re welcome!',
  'thanks girl': 'You\'re welcome!',
  'thanks friend': 'You\'re welcome!',
  'thanks mate': 'You\'re welcome!',
  'thanks pal': 'You\'re welcome!',
  'thanks homie': 'You\'re welcome!',
  'thanks boss': 'You\'re welcome!',
  'thanks chief': 'You\'re welcome!',
  'thanks captain': 'You\'re welcome!',
  'thanks king': 'You\'re welcome!',
  'thanks queen': 'You\'re welcome!',
  'thanks prince': 'You\'re welcome!',
  'thanks princess': 'You\'re welcome!',
  'thanks lord': 'You\'re welcome!',
  'thanks master': 'You\'re welcome!',
  'thanks sensei': 'You\'re welcome!',
  'thanks teacher': 'You\'re welcome!',
  'thanks doctor': 'You\'re welcome!',
  'thanks engineer': 'You\'re welcome!',
  'thanks lawyer': 'You\'re welcome!',
  'thanks pilot': 'You\'re welcome!',
  'thanks driver': 'You\'re welcome!',
  'thanks chef': 'You\'re welcome!',
  'thanks artist': 'You\'re welcome!',
  'thanks musician': 'You\'re welcome!',
  'thanks dancer': 'You\'re welcome!',
  'thanks singer': 'You\'re welcome!',
  'thanks actor': 'You\'re welcome!',
  'thanks actress': 'You\'re welcome!',
  'thanks writer': 'You\'re welcome!',
  'thanks poet': 'You\'re welcome!',
  'thanks philosopher': 'You\'re welcome!',
  'thanks scientist': 'You\'re welcome!',

  // ================================================================
  // 12. Compliments (English) (50)
  // ================================================================
  'nice': 'Nice!',
  'cool': 'Cool!',
  'awesome': 'Awesome!',
  'amazing': 'Amazing!',
  'great': 'Great!',
  'good': 'Good!',
  'excellent': 'Excellent!',
  'perfect': 'Perfect!',
  'brilliant': 'Brilliant!',
  'fantastic': 'Fantastic!',
  'wonderful': 'Wonderful!',
  'beautiful': 'Beautiful!',
  'gorgeous': 'Gorgeous!',
  'stunning': 'Stunning!',
  'incredible': 'Incredible!',
  'unbelievable': 'Unbelievable!',
  'outstanding': 'Outstanding!',
  'superb': 'Superb!',
  'nice!': 'Nice!',
  'cool!': 'Cool!',
  'awesome!': 'Awesome!',
  'amazing!': 'Amazing!',
  'great!': 'Great!',
  'good!': 'Good!',
  'excellent!': 'Excellent!',
  'perfect!': 'Perfect!',
  'brilliant!': 'Brilliant!',
  'fantastic!': 'Fantastic!',
  'wonderful!': 'Wonderful!',
  'beautiful!': 'Beautiful!',
  'gorgeous!': 'Gorgeous!',
  'stunning!': 'Stunning!',
  'incredible!': 'Incredible!',
  'unbelievable!': 'Unbelievable!',
  'outstanding!': 'Outstanding!',
  'superb!': 'Superb!',
  'you are nice': 'You are nice too!',
  'you are cool': 'You are cool too!',
  'you are awesome': 'You are awesome too!',
  'you are amazing': 'You are amazing too!',
  'you are great': 'You are great too!',
  'you are good': 'You are good too!',
  'you are excellent': 'You are excellent too!',
  'you are perfect': 'You are perfect too!',
  'you are brilliant': 'You are brilliant too!',
  'you are fantastic': 'You are fantastic too!',
  'you are wonderful': 'You are wonderful too!',
  'you are beautiful': 'You are beautiful too!',
  'you are gorgeous': 'You are gorgeous too!',
  'you are stunning': 'You are stunning too!',

  // ================================================================
  // 13. Reactions (English) (50)
  // ================================================================
  'lol': 'LOL!',
  'lmao': 'LMAO!',
  'rofl': 'ROFL!',
  'haha': 'Haha!',
  'hehe': 'Hehe!',
  'xd': 'XD',
  'nice one': 'Nice one!',
  'good one': 'Good one!',
  'well done': 'Well done!',
  'good job': 'Good job!',
  'great job': 'Great job!',
  'awesome job': 'Awesome job!',
  'lol!': 'LOL!',
  'lmao!': 'LMAO!',
  'rofl!': 'ROFL!',
  'haha!': 'Haha!',
  'hehe!': 'Hehe!',
  'xd!': 'XD',
  'nice one!': 'Nice one!',
  'good one!': 'Good one!',
  'well done!': 'Well done!',
  'good job!': 'Good job!',
  'great job!': 'Great job!',
  'awesome job!': 'Awesome job!',
  'that\'s funny': 'That\'s funny!',
  'that\'s hilarious': 'That\'s hilarious!',
  'that\'s awesome': 'That\'s awesome!',
  'that\'s amazing': 'That\'s amazing!',
  'that\'s great': 'That\'s great!',
  'that\'s nice': 'That\'s nice!',
  'that\'s cool': 'That\'s cool!',
  'that\'s excellent': 'That\'s excellent!',
  'that\'s perfect': 'That\'s perfect!',
  'that\'s brilliant': 'That\'s brilliant!',
  'that\'s fantastic': 'That\'s fantastic!',
  'that\'s wonderful': 'That\'s wonderful!',
  'that\'s beautiful': 'That\'s beautiful!',
  'that\'s gorgeous': 'That\'s gorgeous!',
  'that\'s stunning': 'That\'s stunning!',
  'that\'s incredible': 'That\'s incredible!',
  'that\'s unbelievable': 'That\'s unbelievable!',
  'that\'s outstanding': 'That\'s outstanding!',
  'that\'s superb': 'That\'s superb!',
  'you are funny': 'You are funny too!',
  'you are hilarious': 'You are hilarious too!',
  'you are awesome': 'You are awesome too!',
  'you are amazing': 'You are amazing too!',
  'you are great': 'You are great too!',
  'you are nice': 'You are nice too!',
  'you are cool': 'You are cool too!',

  // ================================================================
  // 14. Gaming (English) (50)
  // ================================================================
  'gg': 'GG! Well played!',
  'ggwp': 'GGWP!',
  'wp': 'WP!',
  'ez': 'EZ!',
  'noob': 'We all start somewhere!',
  'pro': 'Pro player!',
  'gamer': 'Gamer!',
  'game': 'What game?',
  'win': 'Win!',
  'lose': 'Don\'t worry, next time!',
  'victory': 'Victory!',
  'defeat': 'Defeat, but you fought well!',
  'gg ez': 'GG EZ!',
  'gg!': 'GG! Well played!',
  'ggwp!': 'GGWP!',
  'wp!': 'WP!',
  'ez!': 'EZ!',
  'noob!': 'We all start somewhere!',
  'pro!': 'Pro player!',
  'gamer!': 'Gamer!',
  'game!': 'What game?',
  'win!': 'Win!',
  'lose!': 'Don\'t worry, next time!',
  'victory!': 'Victory!',
  'defeat!': 'Defeat, but you fought well!',
  'good game': 'Good game!',
  'good game!': 'Good game!',
  'well played': 'Well played!',
  'well played!': 'Well played!',
  'nice play': 'Nice play!',
  'nice play!': 'Nice play!',
  'great play': 'Great play!',
  'great play!': 'Great play!',
  'awesome play': 'Awesome play!',
  'awesome play!': 'Awesome play!',
  'amazing play': 'Amazing play!',
  'amazing play!': 'Amazing play!',
  'incredible play': 'Incredible play!',
  'incredible play!': 'Incredible play!',
  'unbelievable play': 'Unbelievable play!',
  'unbelievable play!': 'Unbelievable play!',
  'outstanding play': 'Outstanding play!',
  'outstanding play!': 'Outstanding play!',
  'superb play': 'Superb play!',
  'superb play!': 'Superb play!',
  'brilliant play': 'Brilliant play!',
  'brilliant play!': 'Brilliant play!',
  'fantastic play': 'Fantastic play!',
  'fantastic play!': 'Fantastic play!',
  'wonderful play': 'Wonderful play!',
  'wonderful play!': 'Wonderful play!',
  'beautiful play': 'Beautiful play!',
  'beautiful play!': 'Beautiful play!',

  // ================================================================
  // 15. Goodbye (English) (50)
  // ================================================================
  'bye': 'Bye! See you later',
  'goodbye': 'Goodbye! Take care',
  'see you': 'See you later!',
  'see ya': 'See ya!',
  'cya': 'Cya!',
  'later': 'Later!',
  'take care': 'Take care!',
  'peace': 'Peace out!',
  'adios': 'Adios!',
  'bye bye': 'Bye bye!',
  'bye!': 'Bye! See you later',
  'goodbye!': 'Goodbye! Take care',
  'see you!': 'See you later!',
  'see ya!': 'See ya!',
  'cya!': 'Cya!',
  'later!': 'Later!',
  'take care!': 'Take care!',
  'peace!': 'Peace out!',
  'adios!': 'Adios!',
  'bye bye!': 'Bye bye!',
  'see you later': 'See you later!',
  'see you later!': 'See you later!',
  'see you soon': 'See you soon!',
  'see you soon!': 'See you soon!',
  'see you tomorrow': 'See you tomorrow!',
  'see you tomorrow!': 'See you tomorrow!',
  'see you around': 'See you around!',
  'see you around!': 'See you around!',
  'catch you later': 'Catch you later!',
  'catch you later!': 'Catch you later!',
  'catch ya later': 'Catch ya later!',
  'catch ya later!': 'Catch ya later!',
  'catch you soon': 'Catch you soon!',
  'catch you soon!': 'Catch you soon!',
  'catch you tomorrow': 'Catch you tomorrow!',
  'catch you tomorrow!': 'Catch you tomorrow!',
  'catch you around': 'Catch you around!',
  'catch you around!': 'Catch you around!',
  'take it easy': 'Take it easy!',
  'take it easy!': 'Take it easy!',
  'take care of yourself': 'Take care of yourself!',
  'take care of yourself!': 'Take care of yourself!',
  'have a good day': 'Have a good day!',
  'have a good day!': 'Have a good day!',
  'have a good night': 'Have a good night!',
  'have a good night!': 'Have a good night!',
  'have a good weekend': 'Have a good weekend!',
  'have a good weekend!': 'Have a good weekend!',
  'have a good life': 'Have a good life!',
  'have a good life!': 'Have a good life!',
  'have a good one': 'Have a good one!',
  'have a good one!': 'Have a good one!',

  // ================================================================
  // 16. Mixed / Fun (50)
  // ================================================================
  'باي': 'باي باي يا كبير',
  'سلام': 'سلام عليكم',
  'شكرا': 'عفواً يا محترم',
  'أوكي': 'أوكي يا معلم',
  'ok': 'Okay!',
  'okay': 'Okay!',
  'yeah': 'Yeah!',
  'yep': 'Yep!',
  'nope': 'Nope!',
  'maybe': 'Maybe!',
  'sure': 'Sure!',
  'absolutely': 'Absolutely!',
  'definitely': 'Definitely!',
  'of course': 'Of course!',
  'no problem': 'No problem!',
  'anytime': 'Anytime!',
  'my pleasure': 'My pleasure!',
  'with pleasure': 'With pleasure!',
  'you are stupid': 'No, you are!',
  'stupid': 'Stupid is as stupid does',
  'idiot': 'I\'m not an idiot, I\'m a bot!',
  'dumb': 'Dumb? I\'m smarter than you!',
  'bot': 'I am a bot!',
  'robot': 'Beep boop! I\'m a robot!',
  'ai': 'AI is the future!',
  'ok!': 'Okay!',
  'okay!': 'Okay!',
  'yeah!': 'Yeah!',
  'yep!': 'Yep!',
  'nope!': 'Nope!',
  'maybe!': 'Maybe!',
  'sure!': 'Sure!',
  'absolutely!': 'Absolutely!',
  'definitely!': 'Definitely!',
  'of course!': 'Of course!',
  'no problem!': 'No problem!',
  'anytime!': 'Anytime!',
  'my pleasure!': 'My pleasure!',
  'with pleasure!': 'With pleasure!',
  'you are stupid!': 'No, you are!',
  'stupid!': 'Stupid is as stupid does',
  'idiot!': 'I\'m not an idiot, I\'m a bot!',
  'dumb!': 'Dumb? I\'m smarter than you!',
  'bot!': 'I am a bot!',
  'robot!': 'Beep boop! I\'m a robot!',
  'ai!': 'AI is the future!',
  'what the hell': 'What the hell!',
  'what the hell!': 'What the hell!',
  'what the heck': 'What the heck!',
  'what the heck!': 'What the heck!',

  // ================================================================
  // 17. Emoji replacement (50)
  // ================================================================
  '😂': '😄',
  '🤣': '😄',
  '❤️': '💖',
  '🔥': 'حلوة!',
  '😊': '😊',
  '😄': '😄',
  '😢': 'لا تحزن، أنا هنا معاك',
  '😭': 'لا تبكي، أنا هنا معاك',
  '😍': 'جميل!',
  '😘': 'حب!',
  '😎': 'رائع!',
  '👍': 'شكراً',
  '👎': 'للأسف',
  '❤': '💖',
  '💔': 'آسف',
  '💯': 'ممتاز',
  '🤔': 'تفكير',
  '🧐': 'تفكير',
  '🤨': 'مش متأكد',
  '😏': 'فهمت',
  '😒': 'آسف',
  '😩': 'لا تقلق',
  '😫': 'لا تقلق',
  '😤': 'هدوء',
  '😠': 'هدوء',
  '😡': 'هدوء',
  '🤬': 'هدوء',
  '🥵': 'حار',
  '🥶': 'بارد',
  '🤯': 'مذهل',
  '🥳': 'احتفال',
  '🎉': 'احتفال',
  '🎊': 'احتفال',
  '🎈': 'عيد',
  '🎂': 'عيد ميلاد سعيد',
  '🎁': 'هدية',
  '🎮': 'ألعاب',
  '🕹️': 'ألعاب',
  '⌨️': 'كتابة',
  '🖥️': 'كمبيوتر',
  '📱': 'موبايل',
  '💻': 'لابتوب',
  '🖨️': 'طباعة',
  '📷': 'تصوير',
  '📸': 'تصوير',
  '🎥': 'فيديو',
  '🎬': 'فيلم',
  '📺': 'تلفزيون',
  '📻': 'راديو',
  '🎵': 'موسيقى',
  '🎶': 'موسيقى',

  // ================================================================
  // 18. Random responses (50)
  // ================================================================
  'أنا': 'أنا بوت',
  'أنت': 'أنت رائع',
  'نحن': 'نحن هنا',
  'هم': 'هم هناك',
  'الكل': 'الكل مرحب به',
  'جميع': 'جميعكم مرحب بهم',
  'كل': 'كل شيء تمام',
  'كل شيء': 'كل شيء تمام',
  'كل حاجة': 'كل حاجة تمام',
  'كل شئ': 'كل شئ تمام',
  'كل الناس': 'كل الناس طيبين',
  'كل البشر': 'كل البشر أخوة',
  'كل العالم': 'كل العالم جميل',
  'الكون': 'الكون واسع',
  'السماء': 'السماء جميلة',
  'الأرض': 'الأرض جميلة',
  'البحر': 'البحر واسع',
  'المحيط': 'المحيط عميق',
  'الجبل': 'الجبل عالي',
  'الصحراء': 'الصحراء واسعة',
  'الغابة': 'الغابة خضراء',
  'النهر': 'النهر جاري',
  'الشلال': 'الشلال جميل',
  'الزهرة': 'الزهرة جميلة',
  'الورد': 'الورد جميل',
  'الياسمين': 'الياسمين عطر',
  'الفل': 'الفل عطر',
  'العطر': 'العطر فواح',
  'الطيب': 'الطيب أنت',
  'الجميل': 'الجميل أنت',
  'الرائع': 'الرائع أنت',
  'المميز': 'المميز أنت',
  'الخاص': 'الخاص أنت',
  'العام': 'العام أنت',
  'الشامل': 'الشامل أنت',
  'الكامل': 'الكامل أنت',
  'التام': 'التام أنت',
  'الكبير': 'الكبير أنت',
  'الصغير': 'الصغير أنت',
  'الطويل': 'الطويل أنت',
  'القصير': 'القصير أنت',
  'الرفيع': 'الرفيع أنت',
  'الغليظ': 'الغليظ أنت',
  'النحيف': 'النحيف أنت',
  'السمين': 'السمين أنت',
  'الجديد': 'الجديد أنت',
  'القديم': 'القديم أنت',
  'الحديث': 'الحديث أنت',
  'القديم': 'القديم أنت',
};

// ================================================================
// الرد العام (على أي رسالة)
// ================================================================
export const AUTO_REPLY_MESSAGE = 'مرحباً بك! أنا بوت Void_Syndicate، تحت أمرك';
